project-name: reusing-the-wheel-statik
base-path: /
context:
  static:
    site-title: Reusing the wheel
    language-code: en-us
    top-menu-views:
      - home
      - archives
      - tags
      - projects
    top-menu-pages:
      - about
